#!/usr/bin/env python3
"""Create and validate compact, repository-backed project handoffs."""

import argparse
import base64
import errno
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile
import time

SCHEMA = 2
MARKER = "<!-- Generated by project-checkpoint. Regenerate; do not hand-edit. -->"
META_PREFIX = "<!-- project-checkpoint-meta: "
LEGACY_SECTIONS = ["Identity", "Goal and specification", "Current state", "Decisions that constrain the next task", "Working tree", "Verification evidence", "Risks and blockers", "Exact next action", "Resume prompt"]
SECTIONS = LEGACY_SECTIONS + ["Capability state", "Acceptance criteria", "Open questions"]
MAX_FILE = 512 * 1024 * 1024
MAX_TOTAL = 2 * 1024 * 1024 * 1024
MAX_SECONDS = 30
MAX_GIT_OUTPUT = 16 * 1024 * 1024
MAX_MANIFEST = 40
MAX_HANDOFF = 24 * 1024
MAX_META = 12 * 1024
EXCLUDED = {".git", ".codex-worktrees", "node_modules", "vendor", "cache", ".cache", "build", "dist", "coverage", "archive", "archives"}
SECRET_PATTERNS = [
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"(?i)\b(?:authorization|api[_-]?key|access[_-]?token|secret|password)\s*[:=]\s*\S+"),
    re.compile(r"\b(?:ghp_[A-Za-z0-9]{16,}|github_pat_[A-Za-z0-9_]{16,}|sk-[A-Za-z0-9_-]{16,})\b"),
    re.compile(r"(?i)https?://[^\s/@:]+:[^\s/@]+@"),
]

class CheckpointError(Exception):
    pass

def run_git(root, *args, text=False, check=True, deadline=None, max_output=None):
    command = ["git", "-C", os.fspath(root), *args]
    timeout = None if deadline is None else deadline - time.monotonic()
    if timeout is not None and timeout <= 0:
        raise CheckpointError("Inspection exceeded 30 seconds; reduce repository state and retry.")
    limit = MAX_GIT_OUTPUT if max_output is None else max_output
    with tempfile.TemporaryFile() as stdout, tempfile.TemporaryFile() as stderr:
        try:
            result = subprocess.run(command, stdout=stdout, stderr=stderr, timeout=timeout)
        except subprocess.TimeoutExpired as e:
            raise CheckpointError("Git command exceeded the 30-second inspection limit; reduce repository state and retry.") from e
        for stream in (stdout, stderr):
            if stream.tell() > limit:
                raise CheckpointError(f"Git output exceeds the {limit}-byte limit; reduce dirty or divergent repository state.")
            stream.seek(0)
        output, error = stdout.read(), stderr.read()
    if text:
        output = output.decode("utf-8", "replace")
        error = error.decode("utf-8", "replace")
    p = subprocess.CompletedProcess(command, result.returncode, output, error)
    if check and p.returncode:
        err = p.stderr.strip() if text else p.stderr.decode("utf-8", "replace").strip()
        raise CheckpointError(err or "Git command failed")
    return p

def git_root(project, deadline=None):
    p = Path(project).resolve()
    r = run_git(p, "rev-parse", "--show-toplevel", text=True, check=False, deadline=deadline)
    if r.returncode:
        raise CheckpointError(f"Not a Git worktree: {p}. Select a Git project and retry.")
    root = Path(r.stdout.strip()).resolve()
    if p != root and not (p / ".git").exists():
        raise CheckpointError(f"--project must be the selected worktree root: {root}")
    return root

def display_path(raw):
    safe = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-/ "
    return "".join(chr(b) if b in safe else f"%{b:02X}" for b in raw)

def b64(raw):
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")

def split_z(raw):
    return raw[:-1].split(b"\0") if raw.endswith(b"\0") else raw.split(b"\0")

def status_entries(root, deadline=None):
    chunks = split_z(run_git(root, "status", "--porcelain=v2", "-z", "--untracked-files=all", deadline=deadline).stdout)
    out, i = [], 0
    while i < len(chunks):
        rec = chunks[i]
        if not rec:
            i += 1; continue
        kind = rec[:1]
        if kind == b"1":
            fields = rec.split(b" ", 8); xy, path = fields[1], fields[8]
            out.append((path, xy.decode("ascii"), None, fields[7].decode(), fields[5].decode()))
        elif kind == b"2":
            fields = rec.split(b" ", 9); old = chunks[i + 1]; i += 1
            out.append((fields[9], fields[1].decode("ascii"), old, fields[7].decode(), fields[5].decode()))
        elif kind == b"?":
            out.append((rec[2:], "??", None, "0" * 40, None))
        elif kind == b"u":
            fields = rec.split(b" ", 10); out.append((fields[10], fields[1].decode("ascii"), None, ":".join(x.decode() for x in fields[7:10]), fields[6].decode()))
        i += 1
    return sorted((entry for entry in out if entry[0] != b"HANDOFF.md" and not entry[0].startswith(b".HANDOFF.")), key=lambda x: x[0])

def safe_hash(root, raw, budget, deadline):
    path = os.path.join(os.fsencode(root), raw)
    try: before = os.lstat(path)
    except FileNotFoundError: return "missing", 0, "missing"
    if stat.S_ISLNK(before.st_mode):
        return "symlink:" + hashlib.sha256(os.fsencode(os.readlink(path))).hexdigest(), 0, "120000"
    if not stat.S_ISREG(before.st_mode):
        return "special:" + hashlib.sha256(f"{stat.S_IFMT(before.st_mode)}:{before.st_size}:{before.st_mtime_ns}".encode()).hexdigest(), 0, f"special:{stat.S_IFMT(before.st_mode)}"
    if before.st_size > MAX_FILE:
        raise CheckpointError(f"File exceeds 512 MiB hashing limit: {display_path(raw)}")
    if budget + before.st_size > MAX_TOTAL:
        raise CheckpointError("Changed files exceed the 2 GiB aggregate hashing limit; reduce dirty/untracked state.")
    if time.monotonic() >= deadline: raise CheckpointError("Inspection exceeded 30 seconds; reduce dirty/untracked state and retry.")
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0)
    try: fd = os.open(path, flags)
    except OSError as e:
        if e.errno in (errno.ELOOP, errno.EAGAIN, errno.ENXIO): raise CheckpointError(f"Unsafe or blocking path refused: {display_path(raw)}")
        raise
    h = hashlib.sha256()
    try:
        opened = os.fstat(fd)
        if not stat.S_ISREG(opened.st_mode) or (opened.st_dev, opened.st_ino) != (before.st_dev, before.st_ino):
            raise CheckpointError(f"Path changed during safe open: {display_path(raw)}")
        size = 0
        while True:
            if time.monotonic() >= deadline: raise CheckpointError("Inspection exceeded 30 seconds; reduce dirty/untracked state and retry.")
            block = os.read(fd, min(1024 * 1024, MAX_FILE - size + 1))
            if not block: break
            size += len(block); h.update(block)
            if size > MAX_FILE: raise CheckpointError(f"File exceeds 512 MiB hashing limit: {display_path(raw)}")
        after = os.fstat(fd)
        identity = lambda s: (s.st_mode, s.st_dev, s.st_ino, s.st_size, s.st_mtime_ns, getattr(s, "st_ctime_ns", 0))
        if identity(opened) != identity(after): raise CheckpointError(f"File changed while hashing: {display_path(raw)}")
    finally: os.close(fd)
    mode = "100755" if opened.st_mode & stat.S_IXUSR else "100644"
    return "file:" + h.hexdigest(), size, mode

def head_info(root, deadline=None):
    commit = run_git(root, "rev-parse", "--verify", "HEAD", text=True, check=False, deadline=deadline)
    branch = run_git(root, "symbolic-ref", "--quiet", "--short", "HEAD", text=True, check=False, deadline=deadline)
    if commit.returncode:
        return {"mode": "unborn", "branch": branch.stdout.strip() or "unborn", "commit": "unborn", "subject": "unborn"}
    subject = run_git(root, "show", "-s", "--format=%s", "HEAD", text=True, deadline=deadline).stdout.rstrip("\n")
    return {"mode": "branch" if not branch.returncode else "detached", "branch": branch.stdout.strip() if not branch.returncode else "detached", "commit": commit.stdout.strip(), "subject": subject}

def inspect(root, deadline=None):
    deadline = time.monotonic() + MAX_SECONDS if deadline is None else deadline
    root = git_root(root, deadline=deadline)
    before = run_git(root, "write-tree", text=True, check=False, deadline=deadline).stdout.strip()
    head = head_info(root, deadline); entries = status_entries(root, deadline); total = 0; manifest = []; aggregate = hashlib.sha256(); legacy = hashlib.sha256()
    identity = json.dumps(head, sort_keys=True, ensure_ascii=False).encode()
    aggregate.update(identity); aggregate.update(before.encode()); legacy.update(identity); legacy.update(before.encode())
    for raw, code, old, index, status_mode in entries:
        content, used, safe_mode = safe_hash(root, raw, total, deadline); total += used
        legacy_item = {"path_b64": b64(raw), "path": display_path(raw), "status": code, "index": index, "content": content}
        item = {**legacy_item, "mode": status_mode or safe_mode}
        if old is not None: item.update({"old_path_b64": b64(old), "old_path": display_path(old)})
        if old is not None: legacy_item.update({"old_path_b64": b64(old), "old_path": display_path(old)})
        aggregate.update(json.dumps(item, sort_keys=True, separators=(",", ":")).encode())
        legacy.update(json.dumps(legacy_item, sort_keys=True, separators=(",", ":")).encode())
        if len(manifest) < MAX_MANIFEST: manifest.append(item)
    after = run_git(root, "write-tree", text=True, check=False, deadline=deadline).stdout.strip()
    if before != after or status_entries(root, deadline) != entries: raise CheckpointError("Repository changed during inspection; retry checkpoint.")
    return {**head, "fingerprint": aggregate.hexdigest(), "legacy_fingerprint": legacy.hexdigest(), "manifest": manifest, "path_total": len(entries), "path_omitted": max(0, len(entries)-len(manifest))}

def discover(workspace):
    base = Path(workspace).resolve(); found = []
    for current, dirs, files in os.walk(base):
        rel = Path(current).relative_to(base)
        dirs.sort(); files.sort()
        has_git = ".git" in dirs or ".git" in files
        dirs[:] = sorted(d for d in dirs if d not in EXCLUDED)
        if len(rel.parts) >= 3: dirs[:] = []
        if has_git:
            p = Path(current); marker = p / ".git"; kind = "repository"
            if marker.is_file():
                superproject = run_git(p, "rev-parse", "--show-superproject-working-tree", text=True, check=False)
                kind = "submodule" if not superproject.returncode and superproject.stdout.strip() else "worktree"
            found.append({"path": rel.as_posix() if rel.parts else ".", "kind": kind}); dirs[:] = [d for d in dirs if d != ".git"]
            if len(found) >= 50: return {"candidates": found, "capped": True}
    return {"candidates": found, "capped": False}

def canonical(obj): return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()

def prose_without_meta(text):
    lines = text.replace("\r\n", "\n").replace("\r", "\n").splitlines()
    return "\n".join(line for line in lines if not line.startswith(META_PREFIX)).rstrip() + "\n"

def reject_secrets(value):
    for pattern in SECRET_PATTERNS:
        if pattern.search(value): raise CheckpointError("Potential secret detected; remove or redact it before publishing.")

def safe_text(value):
    value = str(value).replace("\r", " ").replace("\n", " ").strip()
    reject_secrets(value)
    return value.replace("`", "\\`").replace("<", "&lt;").replace(">", "&gt;")

def sanitize_verification(value):
    value = str(value)
    value = re.sub(r"(?<!\S)[A-Za-z_][A-Za-z0-9_]*=\S+", "[env redacted]", value)
    value = re.sub(r"(?i)(--?(?:api[-_]?key|access[-_]?token|token|secret|password|authorization))(?:=|\s+)\S+", r"\1 [redacted]", value)
    return safe_text(value)

def validate_draft(draft):
    if not isinstance(draft, dict): raise CheckpointError("Draft must be a JSON object.")
    allowed = {"goal", "current_state", "capabilities", "decisions", "acceptance_criteria", "verification", "risks", "open_questions", "next_action", "remainder", "references"}
    if set(draft) - allowed: raise CheckpointError("Draft contains unsupported fields.")
    for key in ("goal", "current_state", "next_action"):
        if not isinstance(draft.get(key), str) or not draft[key].strip(): raise CheckpointError(f"Draft field {key} must be a non-empty string.")
    for key in ("capabilities", "decisions", "acceptance_criteria", "verification", "risks", "open_questions", "remainder", "references"):
        if key in draft and (not isinstance(draft[key], list) or not all(isinstance(v, str) for v in draft[key])): raise CheckpointError(f"Draft field {key} must be a list of strings.")
    return draft

def validate_refs(root, refs):
    out = []
    for ref in refs:
        rel = Path(ref)
        if rel.is_absolute() or ".." in rel.parts: raise CheckpointError(f"Reference escapes project: {ref}")
        if rel.parts and rel.parts[0] == ".git": raise CheckpointError(f"Git metadata cannot be referenced: {ref}")
        p = root
        try:
            for part in rel.parts:
                p /= part
                if stat.S_ISLNK(os.lstat(p).st_mode): raise CheckpointError(f"Referenced symlinks are not allowed: {ref}")
        except FileNotFoundError: raise CheckpointError(f"Referenced file does not exist: {ref}")
        if not stat.S_ISREG(os.lstat(p).st_mode): raise CheckpointError(f"Reference is not a regular file: {ref}")
        out.append(rel.as_posix())
    return out

def render(root, draft, evidence):
    validate_draft(draft)
    refs = validate_refs(root, draft.get("references", [])); plan = validate_refs(root, ["PLAN.md"])[0] if os.path.lexists(root / "PLAN.md") else None
    def items(name, fallback="None recorded."):
        vals = draft.get(name, []); clean = sanitize_verification if name == "verification" else safe_text
        return "\n".join(f"- {clean(v)}" for v in vals) if vals else fallback
    goal = safe_text(draft.get("goal", "")); state = safe_text(draft.get("current_state", "")); action = safe_text(draft.get("next_action", ""))
    if not goal or not state or not action: raise CheckpointError("Draft requires non-empty goal, current_state, and next_action.")
    lines = ["# Project Checkpoint", MARKER, "META", "", "## Identity", f"- Git mode: `{evidence['mode']}`", f"- Branch: `{safe_text(evidence['branch'])}`", f"- Commit: `{evidence['commit']}`", f"- Fingerprint: `{evidence['fingerprint']}`", "", "## Goal and specification", goal]
    if plan: lines.append("- Specification: `PLAN.md`")
    if refs: lines.append("- Referenced files: " + ", ".join(f"`{safe_text(r)}`" for r in refs))
    lines += ["", "## Current state", state, "", "## Capability state", items("capabilities"), "", "## Decisions that constrain the next task", items("decisions"), "", "## Acceptance criteria", items("acceptance_criteria"), "", "## Working tree"]
    if evidence["manifest"]:
        lines += [f"- `{i['status']}` " + (f"`{safe_text(i['old_path'])}` -> " if i.get("old_path") else "") + f"`{safe_text(i['path'])}`" for i in evidence["manifest"]]
    else: lines.append("- Clean.")
    if evidence["path_omitted"]: lines.append(f"- {evidence['path_omitted']} additional paths omitted from display; aggregate fingerprint covers all {evidence['path_total']} paths.")
    lines += ["", "## Verification evidence", items("verification", "No verification was recorded for the current work."), "", "## Risks and blockers", items("risks"), "", "## Open questions", items("open_questions"), "", "## Exact next action", action]
    remainder = draft.get("remainder", [])
    if remainder: lines += ["", "Later remainder:"] + [f"{n}. {safe_text(v)}" for n, v in enumerate(remainder, 1)]
    lines += ["", "## Resume prompt", "Use $project-checkpoint to resume this project. Validate HANDOFF.md and classify the current branch relation first; recover the structured capability, decision, acceptance, verification, risk, and open-question context. Read PLAN.md when referenced, then only explicitly referenced files or files required by my request. Report evidence-supported drift and never overwrite the checkpoint during resume.", ""]
    provisional = "\n".join(line for line in lines if line != "META")
    meta = {"schema": SCHEMA, "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), **{k:evidence[k] for k in ("mode","branch","commit","fingerprint","manifest","path_total","path_omitted")}, "plan": plan, "references": refs, "prose_sha256": hashlib.sha256(prose_without_meta(provisional).encode()).hexdigest()}
    encoded = canonical(meta)
    if len(encoded) > MAX_META: raise CheckpointError("Metadata exceeds 12 KiB; reduce display-manifest entries.")
    text = "\n".join(META_PREFIX + b64(encoded) + " -->" if line == "META" else line for line in lines)
    validate_handoff(text)
    return text

def validate_handoff(text, schema=SCHEMA):
    raw = text.encode()
    if len(raw) > MAX_HANDOFF: raise CheckpointError("HANDOFF.md exceeds 24 KiB; reduce narrative or display-manifest entries.")
    if len(text.splitlines()) > 120: raise CheckpointError("HANDOFF.md exceeds 120 lines; reduce narrative or display-manifest entries.")
    if len(re.findall(r"\b\w+\b", text)) > 1000: raise CheckpointError("HANDOFF.md exceeds 1,000 words; reduce narrative.")
    for section in SECTIONS if schema >= 2 else LEGACY_SECTIONS:
        if text.count(f"## {section}") != 1: raise CheckpointError(f"Missing or duplicate required section: {section}")
    if re.search(r"\b(?:TODO|TBD|FIXME|<[^>]+>)\b", text): raise CheckpointError("Unresolved placeholder detected in handoff.")
    reject_secrets(text)

def parse_handoff(text):
    validate_handoff(text, 1)
    if MARKER not in text: raise CheckpointError("HANDOFF.md is not generated by project-checkpoint.")
    lines = [l for l in text.splitlines() if l.startswith(META_PREFIX)]
    if len(lines) != 1 or not lines[0].endswith(" -->"): raise CheckpointError("Missing or duplicate canonical metadata.")
    token = lines[0][len(META_PREFIX):-4]; raw = base64.urlsafe_b64decode(token + "=" * (-len(token) % 4))
    if len(raw) > MAX_META: raise CheckpointError("Decoded metadata exceeds 12 KiB.")
    try: meta = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as e: raise CheckpointError("Metadata is not valid canonical JSON.") from e
    validate_metadata(meta)
    validate_handoff(text, meta["schema"])
    if canonical(meta) != raw: raise CheckpointError("Metadata JSON is not canonical.")
    if hashlib.sha256(prose_without_meta(text).encode()).hexdigest() != meta.get("prose_sha256"): raise CheckpointError("HANDOFF.md prose was edited after generation.")
    return meta

def section_lines(text, section):
    lines = text.splitlines(); start = lines.index(f"## {section}") + 1; out = []
    for line in lines[start:]:
        if line.startswith("## "): break
        out.append(line)
    return out

def section_first_line(text, section):
    for line in section_lines(text, section):
        if line.strip(): return line.strip()
    raise CheckpointError(f"Handoff section is empty: {section}")

def section_items(text, section):
    if f"## {section}" not in text.splitlines(): return []
    return [line[2:].strip() for line in section_lines(text, section) if line.startswith("- ")]

def section_remainder(text):
    out, active = [], False
    for line in section_lines(text, "Exact next action"):
        if line == "Later remainder:": active = True; continue
        match = re.fullmatch(r"\d+\. (.+)", line) if active else None
        if match: out.append(match.group(1))
    return out

def validate_metadata(meta):
    keys = {"schema","generated_at","mode","branch","commit","fingerprint","manifest","path_total","path_omitted","plan","references","prose_sha256"}
    if not isinstance(meta, dict) or set(meta) != keys: raise CheckpointError("Metadata has missing or unsupported keys.")
    if type(meta["schema"]) is not int or meta["schema"] not in {1, SCHEMA} or not isinstance(meta["mode"], str) or meta["mode"] not in {"branch","detached","unborn"}: raise CheckpointError("Metadata schema or Git mode is invalid.")
    if not isinstance(meta["branch"], str) or not isinstance(meta["commit"], str) or not re.fullmatch(r"(?:unborn|[0-9a-f]{40,64})", meta["commit"]): raise CheckpointError("Metadata branch or commit is invalid.")
    if not all(isinstance(meta[k], str) and re.fullmatch(r"[0-9a-f]{64}", meta[k]) for k in ("fingerprint", "prose_sha256")): raise CheckpointError("Metadata digest is invalid.")
    try: time.strptime(meta["generated_at"], "%Y-%m-%dT%H:%M:%SZ")
    except (TypeError, ValueError): raise CheckpointError("Metadata generation time is invalid.")
    if type(meta["path_total"]) is not int or type(meta["path_omitted"]) is not int or min(meta["path_total"], meta["path_omitted"]) < 0 or meta["path_omitted"] > meta["path_total"]: raise CheckpointError("Metadata path counts are invalid.")
    if meta["plan"] not in (None, "PLAN.md"): raise CheckpointError("Metadata plan is invalid.")
    if not isinstance(meta["references"], list) or not all(isinstance(v, str) for v in meta["references"]): raise CheckpointError("Metadata references are invalid.")
    if not isinstance(meta["manifest"], list) or len(meta["manifest"]) > MAX_MANIFEST: raise CheckpointError("Metadata manifest is invalid.")
    if len(meta["manifest"]) != min(meta["path_total"], MAX_MANIFEST) or meta["path_omitted"] != max(0, meta["path_total"] - MAX_MANIFEST): raise CheckpointError("Metadata manifest counts violate the bounded contract.")
    for item in meta["manifest"]:
        required = {"path_b64","path","status","index","content"} | ({"mode"} if meta["schema"] >= 2 else set()); optional = {"old_path_b64","old_path"}
        if not isinstance(item, dict) or not required <= set(item) or set(item) - required - optional or not all(isinstance(v, str) for v in item.values()): raise CheckpointError("Metadata manifest entry is invalid.")
        if ({"old_path_b64","old_path"} & set(item)) not in (set(), {"old_path_b64","old_path"}): raise CheckpointError("Metadata rename path pair is invalid.")
        if not re.fullmatch(r"[.MADRCTU?!]{2}", item["status"]) or not re.fullmatch(r"[0-9a-f]{40,64}(?::[0-9a-f]{40,64}:[0-9a-f]{40,64})?", item["index"]): raise CheckpointError("Metadata status or index identity is invalid.")
        if not re.fullmatch(r"(?:missing|(?:file|symlink|special):[0-9a-f]{64})", item["content"]): raise CheckpointError("Metadata content identity is invalid.")
        if meta["schema"] >= 2 and not re.fullmatch(r"(?:missing|[0-9]{6}|special:[0-9]+)", item["mode"]): raise CheckpointError("Metadata worktree mode is invalid.")
        for encoded, displayed in (("path_b64","path"),("old_path_b64","old_path")):
            if encoded not in item: continue
            token = item[encoded]
            if len(token) > 5462 or not re.fullmatch(r"[A-Za-z0-9_-]*", token): raise CheckpointError("Metadata path encoding is invalid.")
            try: decoded = base64.urlsafe_b64decode(token + "=" * (-len(token) % 4))
            except ValueError as e: raise CheckpointError("Metadata path encoding is invalid.") from e
            if b64(decoded) != token or display_path(decoded) != item[displayed]: raise CheckpointError("Metadata path does not round-trip canonically.")

def read_regular(path, limit=MAX_HANDOFF, expected=None):
    try: before = os.lstat(path)
    except FileNotFoundError: raise
    if not stat.S_ISREG(before.st_mode): raise CheckpointError("HANDOFF.md must be a regular file, not a symlink or special file.")
    if before.st_size > limit: raise CheckpointError("HANDOFF.md exceeds the bounded read limit.")
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0)
    try: fd = os.open(path, flags)
    except OSError as e:
        if e.errno in (errno.ELOOP, errno.EAGAIN, errno.ENXIO): raise CheckpointError("Unsafe or blocking HANDOFF.md refused.")
        raise
    try:
        opened = os.fstat(fd); identity = lambda s: (s.st_dev, s.st_ino, s.st_size, s.st_mtime_ns, getattr(s, "st_ctime_ns", 0))
        if not stat.S_ISREG(opened.st_mode) or (opened.st_dev, opened.st_ino) != (before.st_dev, before.st_ino) or (expected and (opened.st_dev, opened.st_ino) != expected): raise CheckpointError("HANDOFF.md changed during safe open.")
        data = bytearray()
        while len(data) <= limit:
            block = os.read(fd, min(65536, limit + 1 - len(data)))
            if not block: break
            data.extend(block)
        if len(data) > limit: raise CheckpointError("HANDOFF.md exceeds the bounded read limit.")
        if identity(opened) != identity(os.fstat(fd)): raise CheckpointError("HANDOFF.md changed while reading.")
        return bytes(data), opened
    finally: os.close(fd)

def authorize_target(target, approved):
    try: st = os.lstat(target)
    except FileNotFoundError: return {"absent": True}
    if not stat.S_ISREG(st.st_mode): raise CheckpointError("Existing HANDOFF.md must be a regular file, not a symlink or special file.")
    data, opened = read_regular(target)
    if MARKER.encode() not in data and not approved: raise CheckpointError(f"Refusing to overwrite unowned HANDOFF.md at {target}; explicitly approve that exact path.")
    return {"absent": False, "identity": (opened.st_dev, opened.st_ino), "digest": hashlib.sha256(data).hexdigest()}

def target_unchanged(target, auth):
    try: st = os.lstat(target)
    except FileNotFoundError: return auth["absent"]
    if auth["absent"] or not stat.S_ISREG(st.st_mode) or (st.st_dev, st.st_ino) != auth["identity"]: return False
    try: data, _ = read_regular(target, expected=auth["identity"])
    except (CheckpointError, OSError): return False
    return hashlib.sha256(data).hexdigest() == auth["digest"]

def fsync_directory(path):
    if os.name == "nt": return
    try:
        fd = os.open(path, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try: os.fsync(fd)
        finally: os.close(fd)
    except OSError as e:
        if e.errno not in {errno.EBADF, errno.EINVAL, getattr(errno, "ENOTSUP", errno.EINVAL)}: raise

def publish(root, draft, approved=False):
    root = git_root(root); target = root / "HANDOFF.md"; auth = authorize_target(target, approved); evidence = inspect(root); text = render(root, draft, evidence)
    fd, temp = tempfile.mkstemp(prefix=".HANDOFF.", dir=root)
    try:
        with os.fdopen(fd, "wb") as f: f.write(text.encode()); f.flush(); os.fsync(f.fileno())
        if inspect(root)["fingerprint"] != evidence["fingerprint"]: raise CheckpointError("Repository changed before publication; retry checkpoint.")
        if not target_unchanged(target, auth): raise CheckpointError("HANDOFF.md changed after overwrite authorization; retry.")
        os.replace(temp, target)
        fsync_directory(root)
    finally:
        try: os.unlink(temp)
        except FileNotFoundError: pass
    return evidence

def commit_delta(root, saved_commit, current_commit, saved_branch, current_branch, deadline=None):
    if saved_commit == current_commit:
        return {"relation": "exact" if saved_branch == current_branch else "branch-created", "ahead": 0, "behind": 0, "paths": [], "known": True}
    if "unborn" in {saved_commit, current_commit}:
        return {"relation": "unknown", "ahead": None, "behind": None, "paths": [], "known": False}
    for commit in (saved_commit, current_commit):
        if run_git(root, "cat-file", "-e", f"{commit}^{{commit}}", check=False, deadline=deadline).returncode:
            return {"relation": "unknown", "ahead": None, "behind": None, "paths": [], "known": False}
    counts = run_git(root, "rev-list", "--left-right", "--count", f"{saved_commit}...{current_commit}", text=True, deadline=deadline).stdout.split()
    behind, ahead = map(int, counts)
    relation = "advanced" if not behind else "rewound" if not ahead else "diverged"
    raw = split_z(run_git(root, "diff", "--name-only", "-z", saved_commit, current_commit, "--", deadline=deadline).stdout)
    paths = [display_path(path) for path in raw if path and path != b"HANDOFF.md" and not path.startswith(b".HANDOFF.")]
    return {"relation": relation, "ahead": ahead, "behind": behind, "paths": paths, "known": True}

def resume(root):
    deadline = time.monotonic() + MAX_SECONDS
    root = git_root(root, deadline=deadline); target = root / "HANDOFF.md"
    try: data, _ = read_regular(target)
    except FileNotFoundError: raise CheckpointError("A regular generated HANDOFF.md is required to resume.")
    try: text = data.decode("utf-8")
    except UnicodeDecodeError as e: raise CheckpointError("HANDOFF.md must be valid UTF-8.") from e
    meta = parse_handoff(text); validate_refs(root, ([meta["plan"]] if meta.get("plan") else []) + meta["references"]); current = inspect(root, deadline)
    fingerprint = current["fingerprint"] if meta["schema"] >= 2 else current["legacy_fingerprint"]
    fresh = current["commit"] == meta["commit"] and fingerprint == meta["fingerprint"]
    comparable = lambda item: item if meta["schema"] >= 2 else {k:v for k,v in item.items() if k != "mode"}
    saved = {i["path_b64"]: i for i in meta["manifest"]}; now = {i["path_b64"]: comparable(i) for i in current["manifest"]}
    changed = sorted({*(saved.keys()), *(now.keys())}, key=str)
    dirty_paths = [now.get(k, saved.get(k))["path"] for k in changed if saved.get(k) != now.get(k)] if not meta["path_omitted"] and not current["path_omitted"] else []
    delta = commit_delta(root, meta["commit"], current["commit"], meta["branch"], current["branch"], deadline)
    all_paths = sorted(set(delta["paths"] + dirty_paths)); paths = all_paths[:MAX_MANIFEST]
    complete = delta["known"] and not meta["path_omitted"] and not current["path_omitted"] and len(all_paths) <= MAX_MANIFEST
    inherited = delta["relation"] == "branch-created" and complete and not paths
    status = "fresh" if fresh else "inherited" if inherited else "drifted" if delta["relation"] in {"exact", "branch-created"} else delta["relation"]
    return {
        "schema": meta["schema"], "generated_at": meta["generated_at"], "resume_status": status, "fresh": fresh,
        "goal": section_first_line(text, "Goal and specification"), "current_state": section_first_line(text, "Current state"),
        "capabilities": section_items(text, "Capability state"), "decisions": section_items(text, "Decisions that constrain the next task"),
        "acceptance_criteria": section_items(text, "Acceptance criteria"), "verification": section_items(text, "Verification evidence"),
        "risks": section_items(text, "Risks and blockers"), "open_questions": section_items(text, "Open questions"),
        "next_action": section_first_line(text, "Exact next action"), "remainder": section_remainder(text),
        "plan": meta["plan"], "references": meta["references"], "saved_commit": meta["commit"], "current_commit": current["commit"],
        "saved_branch": meta["branch"], "current_branch": current["branch"], "branch_relation": delta["relation"],
        "ahead": delta["ahead"], "behind": delta["behind"], "changed_paths": paths, "complete_path_comparison": complete,
        "verification_current": status in {"fresh", "inherited"},
    }

def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__); sub = p.add_subparsers(dest="command", required=True)
    d = sub.add_parser("discover"); d.add_argument("--workspace", required=True)
    for name in ("inspect", "resume"):
        q = sub.add_parser(name); q.add_argument("--project", required=True)
    q = sub.add_parser("publish"); q.add_argument("--project", required=True); q.add_argument("--input", required=True); q.add_argument("--approve-overwrite", action="store_true")
    args = p.parse_args(argv)
    try:
        if args.command == "discover": result = discover(args.workspace)
        elif args.command == "inspect": result = inspect(args.project)
        elif args.command == "resume": result = resume(args.project)
        else:
            with open(args.input, encoding="utf-8") as f: draft = json.load(f)
            evidence = publish(args.project, draft, args.approve_overwrite)
            result = {"published": True, **{k:evidence[k] for k in ("branch", "commit", "fingerprint", "path_total")}}
        print(json.dumps(result, sort_keys=True))
    except (CheckpointError, OSError, ValueError, json.JSONDecodeError) as e:
        print(f"project-checkpoint: {e}", file=sys.stderr); return 2
    return 0

if __name__ == "__main__": raise SystemExit(main())
